### ISSUE TITLE
If camera component is added to entity in scene, splat will not render

### ISSUE THREAD

**Issue by kfarr** [quadjr/aframe-gaussian-splatting#21]
Here's a simplified example of code that will prevent splat from rendering:
```
    <a-scene>
      <a-entity gaussian_splatting="src: https://huggingface.co/cakewalk/splat-data/resolve/main/train.splat;"></a-entity>
      <!-- the following line makes the splat not render -->
      <a-entity id="player" camera position="0 1.6 0" look-controls></a-entity>
    </a-scene>
```

Error reproduction: https://glitch.com/edit/#!/phantom-copper-sphere?path=index.html%3A15%3A0
(remove line 13 to see it work correctly)

console error:
```
index.js:16 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'el')
    at n.init (index.js:16:40)
    at n.initComponent (component.js:318:10)
    at n.updateProperties (component.js:300:12)
    at e.exports.Component (component.js:76:8)
    at new n (component.js:660:15)
    at d.initComponent (a-entity.js:319:17)
    at d.updateComponent (a-entity.js:471:10)
    at d.updateComponents (a-entity.js:442:12)
    at a-entity.js:243:12
    at a-node.js:150:17
```

**Comment by kfarr** [comment]
Ok I'm not sure why but it appears that if an entity on the scene includes a `camera` component, then `this` is not available when `init` lifecycle method is first run on `gaussian_splatting` component.

A hack is to wrap the loading event with 1 second timeout
```
		setTimeout(() => {
			this.loadData(this.el.sceneEl.camera.el.components.camera.camera, this.el.object3D, this.el.sceneEl.renderer, this.data.src);
			if (!!this.data.cutoutEntity) {
				this.cutout = this.data.cutoutEntity.object3D;
			}
		}, 1000);
```

Instead we should probably listen to some sort of event being finished?

**Comment by kfarr** [comment]
> Instead we should probably listen to some sort of event being finished?

Yes, the webxr discord said wait until the a-frame scene loaded. See #23 ready for review
